// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace MainApplication
{
    [default_interface]
    runtimeclass SplashScreen : Microsoft.UI.Xaml.Window
    {
        SplashScreen();
    }
}
